// Dashboard data only. The full per-match analysis and three-tier plans live in
// the report (report.html, generated by build_report.py) — the site embeds that
// untouched. Here we only model what the profit dashboard needs.

// `text` is the always-present human label (legacy + fallback). The structured
// fields mirror a real 竞彩 票面 so the card can render 主队 VS 客队 / 第N场 编号 /
// 玩法类别 / 选择@赔率 — all optional, so older data still renders via `text`.
export type TicketLeg = {
  text: string;
  odds?: number;
  hit?: boolean | null;
  matchNo?: string; // 赛事编号，如 "周五029"
  home?: string; // 主队
  away?: string; // 客队
  category?: string; // 玩法类别，如 "胜平负" / "半全场胜平负"
  pick?: string; // 选择文案，如 "胜" / "负" / "胜胜"
  stake?: number; // 独立多注票里该注本金（如「单场固定」每注 2 元）
  payout?: number; // 独立多注票里该注命中回报
};

export type TicketStatus = "win" | "loss" | "pending";

export type Ticket = {
  id: string;
  tier: string; // 稳健 / 平衡 / 激进 / 自选
  type: string; // 单关 / 2串1 / 3串1 / 单场固定 …
  mode?: "independent"; // 独立多注票：每注各自单关、独立结算（不连乘）
  martingale?: boolean; // 比分叠层（翻倍追分）链上的一轮
  legs: TicketLeg[];
  stake: number;
  multiple?: number; // 倍数（如 5 倍）；缺省按 本金/2 推（竞彩 2 元/注）
  combos?: number; // 复式/系统过关注数（如 5场4关=28注）；有则按「N注·命中X场」展示，不显示单一连乘赔率
  combinedOdds: number;
  status: TicketStatus;
  payout: number; // total returned (0 on loss / pending)
  profit: number; // payout - stake on win, -stake on loss, 0 pending
};

// 比分叠层（翻倍 / 马丁格尔）：每轮买 scoresPerRound 个候选比分、每注翻倍，中一个收官。
// 由 export_site_data.py 从带 martingale 标记的比分票按日序还原，写进 index.json。
export type MartingaleCycle = {
  wonDate: string; // 收官（命中）那天
  layers: number; // 第几层命中
  multiple: number; // 命中层倍数（每比分本金 / baseUnit）
  hitPick: string | null; // 命中比分，如 "挪威 3:2 塞内加尔"
  hitOdds: number | null;
  payout: number;
  cost: number; // 整轮累计投入（翻倍口径）
  net: number; // 整轮净盈亏 = payout - cost
};

export type MartingaleRound = {
  date: string;
  multiple: number;
  perScore: number;
  total: number;
  status: TicketStatus;
  profit: number;
  won: boolean;
  hitPick: string | null;
  hitOdds: number | null;
  payout: number;
};

export type MartingaleCurrent = {
  layer: number; // 已叠到第几层
  multiple: number; // 当前层倍数
  cumLoss: number; // 累计已亏（翻倍口径）
  rounds: MartingaleRound[];
  nextLayer: number;
  nextMultiple: number;
  nextPerScore: number; // 下一层 元/比分
  nextTotal: number; // 下一层两注合计
  nextNetIfHit: number; // 下一层命中净赚（按 assumedOdds）
};

export type Martingale = {
  baseUnit: number; // 元/比分
  scoresPerRound: number;
  assumedOdds: number; // 估算「命中可赚」用的比分赔率
  current: MartingaleCurrent | null;
  history: MartingaleCycle[]; // 已命中收官的轮，新→旧
};

export type DayData = {
  date: string; // YYYY-MM-DD
  weekday?: string;
  status: "open" | "settled";
  hasReport: boolean; // whether report.html exists for this date
  summary?: string;
  tickets?: Ticket[];
  dayProfit?: number | null;
  dayStake?: number | null;
};

export type IndexDay = {
  date: string;
  weekday?: string;
  status: "open" | "settled";
  hasReport: boolean;
  dayProfit: number | null;
};

export type SiteIndex = {
  updatedAt?: string;
  days: IndexDay[]; // newest first
  reportDates: string[]; // dates that have a report, newest first
  cumulativeProfit: number;
  totalStake: number;
  totalTickets: number;
  winTickets: number;
  profitSeries: { date: string; profit: number }[]; // settled days, oldest first
  martingale?: Martingale | null; // 比分叠层（翻倍追分）状态
};
