// Dashboard data only. The full per-match analysis and three-tier plans live in
// the report (report.html, generated by build_report.py) — the site embeds that
// untouched. Here we only model what the profit dashboard needs.

// `text` is the always-present human label (legacy + fallback). The structured
// fields mirror a real 竞彩 票面 so the card can render 主队 VS 客队 / 第N场 编号 /
// 玩法类别 / 选择@赔率 — all optional, so older data still renders via `text`.
export type TicketLeg = {
  text: string;
  odds?: number;
  hit?: boolean | null;
  matchNo?: string; // 赛事编号，如 "周五029"
  home?: string; // 主队
  away?: string; // 客队
  category?: string; // 玩法类别，如 "胜平负" / "半全场胜平负"
  pick?: string; // 选择文案，如 "胜" / "负" / "胜胜"
};

export type TicketStatus = "win" | "loss" | "pending";

export type Ticket = {
  id: string;
  tier: string; // 稳健 / 平衡 / 激进 / 自选
  type: string; // 单关 / 2串1 / 3串1 …
  legs: TicketLeg[];
  stake: number;
  multiple?: number; // 倍数（如 5 倍）；缺省按 本金/2 推（竞彩 2 元/注）
  combinedOdds: number;
  status: TicketStatus;
  payout: number; // total returned (0 on loss / pending)
  profit: number; // payout - stake on win, -stake on loss, 0 pending
};

export type DayData = {
  date: string; // YYYY-MM-DD
  weekday?: string;
  status: "open" | "settled";
  hasReport: boolean; // whether report.html exists for this date
  summary?: string;
  tickets?: Ticket[];
  dayProfit?: number | null;
  dayStake?: number | null;
};

export type IndexDay = {
  date: string;
  weekday?: string;
  status: "open" | "settled";
  hasReport: boolean;
  dayProfit: number | null;
};

export type SiteIndex = {
  updatedAt?: string;
  days: IndexDay[]; // newest first
  reportDates: string[]; // dates that have a report, newest first
  cumulativeProfit: number;
  totalStake: number;
  totalTickets: number;
  winTickets: number;
  profitSeries: { date: string; profit: number }[]; // settled days, oldest first
};
